#!/usr/bin/env bash

SANV_DIR="$(cd "$(dirname "$(realpath "$0")")" && pwd)"

source "$SANV_DIR/vars"

load_libs() {
  for FILE in "$LIB_DIR"/*; do
    source "$FILE"
  done
}

load_opts() {
  for FILE in "$OPTS_DIR"/*; do
    source "$FILE"
  done
}

load_libs
load_opts
check_commands
check_sanv_executable
check_installation_dir
check_arch
format_version
execute_option
