#!/usr/bin/env bash

VM3S_SYMLINK_PATH=/usr/local/bin/vm3s
VM3S_OPT="$1"
NODE_VERSION="$2"
VM3S_DIR="$(cd "$(dirname "$(realpath "$0")")" && pwd)"
VM3S_PATH="$VM3S_DIR/vm3s"
INSTALL_DIR="$VM3S_DIR/versions"
VERSION_DIR="$INSTALL_DIR"/"$NODE_VERSION"
VERSION_MAJOR_REGEX="^[0-9]{1,2}$"
VERSION_WITH_DOTS_REGEX="^[0-9]{1,2}(\.[0-9]{1,2}){2}$"
VALID_OPTS=("install" "list" "search" "remove" "use")

if [[ ! -L "$VM3S_SYMLINK_PATH" ]]; then
  sudo chmod +x "$VM3S_PATH"
  sudo ln -s "$VM3S_PATH" "$VM3S_SYMLINK_PATH"
  sudo chmod +x "$VM3S_SYMLINK_PATH"
fi

if [[ ! -d "$INSTALL_DIR" ]]; then
  mkdir "$INSTALL_DIR"
fi

if [[ ! "${VALID_OPTS[@]}" =~ "${VM3S_OPT}" ]]; then
  echo "A valid OPTION is required. Ex: install | search | list | use | remove"
fi

if [[ -z "$NODE_VERSION" && "$VM3S_OPT" != "search" && "$VM3S_OPT" != "list" ]]; then
  echo "VERSION is required. Ex: latest | 22 | 22.13.0"
  exit 1
fi

if [[ "$VM3S_OPT" = "install" ]]; then
  if [[ -d "$VERSION_DIR" ]]; then
    echo "$NODE_VERSION already intalled."
    exit 1
  fi

  URL="https://nodejs.org/dist/"

  if [[ "$NODE_VERSION" =~ $VERSION_MAJOR_REGEX ]]; then
    URL="${URL}latest-v$NODE_VERSION.x/node-latest-v$NODE_VERSION.x-linux-x64.tar.xz"

  elif [[ "$NODE_VERSION" =~ $VERSION_WITH_DOTS_REGEX ]]; then
    URL="${URL}v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz"

  else
    URL="${URL}$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.xz"
  fi

  mkdir "$VERSION_DIR"

  curl -L -o- "$URL" |
    tar -xJ -C "$VERSION_DIR" --strip-components=1

  if [[ $? -ne 0 ]]; then
    echo "Error: Failed curl $URL"

    sudo rm -rf /usr/local/bin/node
    sudo rm -rf /usr/local/bin/npm
  fi

  sudo rm -rf /usr/local/bin/node
  sudo rm -rf /usr/local/bin/npm

  sudo chmod +x "$VERSION_DIR"/bin/node
  sudo chmod +x "$VERSION_DIR"/bin/npm

  sudo ln -s "$VERSION_DIR"/bin/node /usr/local/bin/
  sudo ln -s "$VERSION_DIR"/bin/npm /usr/local/bin/
fi

# if [[ "$COMMAND" = "search" ]]; then
#   echo ">>> search"
# fi
#
if [[ "$VM3S_OPT" = "list" ]]; then
  ls "$INSTALL_DIR"
fi
#
# if [[ "$COMMAND" = "use" ]]; then
#   echo ">>> use"
# fi
#
#
if [[ "$VM3S_OPT" = "remove" ]]; then
  if [[ ! -d "$INSTALL_DIR"/"$NODE_VERSION" ]]; then
    echo "$NODE_VERSION version not found."
    exit 1
  fi

  sudo rm -rf /usr/local/bin/node
  sudo rm -rf /usr/local/bin/npm
  sudo rm -rf "$VERSION_DIR"
fi
