#!/usr/bin/env bash

use() {
  ALL_VERSIONS=$(ls $INSTALL_DIR)

  if [[ -z "$ALL_VERSIONS" ]]; then
    log_message info "No installed versions found."
    exit 1
  else
    fzf_prompt set_version
  fi
}
