#!/usr/bin/env bash

check_commands() {
  if [[ 
    "$SANV_OPT" != "install" &&
    "$SANV_OPT" != "version" &&
    "$SANV_OPT" != "search" &&
    "$SANV_OPT" != "list" &&
    "$SANV_OPT" != "use" &&
    "$SANV_OPT" != "remove" ]]; then
    log_message error "Invalid OPTION: '${SANV_OPT}'. A valid OPTION is required: install | search | list | use | remove."
    exit 1
  fi
}
