#!/usr/bin/env bash

get_real_version_from_url() {
  local REDIRECT_URL
  local VERSION

  URL="${URL}$NODE_VERSION/node-$NODE_VERSION-linux-$SYSTEM_ARCH.tar.xz"

  REDIRECT_URL=$(curl -sIL -w "%{url_effective}" -o /dev/null "$URL")
  NODE_VERSION_COMPLETE=$(echo $REDIRECT_URL | grep -oP '(?<=v)[0-9]+\.[0-9]+\.[0-9]+' | head -1)
  NODE_VERSION_COMPLETE="v$NODE_VERSION_COMPLETE"

  if [[ $NODE_VERSION_COMPLETE == "v" ]]; then
    log_message warning "No version found."
    exit 1
  fi
}
