#!/usr/bin/env bash

set_version() {
  if [[ -L "$NODE_BIN_PATH" ]]; then
    sudo rm -rf "$NODE_BIN_PATH"
  fi

  if [[ -L "$NPM_BIN_PATH" ]]; then
    sudo rm -rf "$NPM_BIN_PATH"
  fi

  sudo chmod +x "$INSTALL_DIR/$NODE_VERSION_COMPLETE"/bin/node
  sudo chmod +x "$INSTALL_DIR/$NODE_VERSION_COMPLETE"/bin/npm

  sudo ln -s "$INSTALL_DIR/$NODE_VERSION_COMPLETE"/bin/node "$BIN_DIR"
  sudo ln -s "$INSTALL_DIR/$NODE_VERSION_COMPLETE"/bin/npm "$BIN_DIR"

  log_message success "$(node -v)"
}
